### ISSUE TITLE
Allow FS Layers from AGOL

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#182]
ArcGIS Online only publishes hosted/uploaded content as a "FeatureServer" yet builder only allows use of URL's that end in "MapServer". Sure would be handy to be able to use AGOL Feature Services in Builder.

**Comment by nateirwin** [comment]
Can you give me a URL endpoint to a feature service hosted on ArcGIS Online? I can take care of this when I have an endpoint to test against.

**Comment by tpcolson** [comment]
http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_TRAIL_INVENTORY/FeatureServer/0

http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_TRAILS/FeatureServer/0

http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_RESTROOMS/FeatureServer/0

**Comment by nateirwin** [comment]
This is done, although you’ll need to load feature services as `geojson` layer types. Now that ArcGIS Online supports exporting data from feature services as GeoJSON, you can load the data directly by specifying the `f=geojson` parameter in the URL: `http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_RESTROOMS/FeatureServer/0/query?f=geojson&outSR=4326&where=OBJECTID+IS+NOT+NULL`. Also note that you *may need to specify the `outSR` parameter so the data come down in decimal degrees.

If you want to load data from a feature service that is self-hosted via ArcGIS Server, you’ll need to pass the URL through a little proxy we wrote like this: `https://npmap-arcgis-proxy.herokuapp.com/layer2geojson?url=http://mobilegis.nps.gov/arcgis/rest/services/IncidentDataCollection_3/FeatureServer/1`. This is because ArcGIS Server does not yet support exporting in GeoJSON format. Esri has said that this will be supported in a release soon.

Take a look at this example: http://www.nps.gov/npmap/npmap.js/2.0.0/examples/arcgisserver-layer.html and do a view source to see all of this in context.

**Comment by tpcolson** [comment]
Works Great Nate! For others doing this, see http://sampleserver1.arcgisonline.com/ArcGIS/SDK/REST/index.html?query.html for additional extensions, e.g you want to filter on additional fields and/or include fields in the output e.g. http://services1.arcgis.com/fBc8EJBxQRMcHlei/arcgis/rest/services/GRSM_TRAIL_INVENTORY/FeatureServer/0/query?f=geojson&outSR=4326&where=SIGNSTATUS=1&outFields=*
