### ISSUE TITLE
Can't change symbology on CartoDB layers

### ISSUE THREAD

**Issue by makella** [nationalparkservice/npmap-builder#209]
I added a bunch of CartoDB layers to a Builder map.  After adding all of them, I wanted to start symbolizing them.  I am unable to change the color or any other properties.

Here is the map id: 24f99863-a275-4001-8203-20224198b4ed

**Comment by alexNPS** [comment]
I just noticed this, too, on 61421598-a8ba-4a78-bc2b-72e592ffeab7. While we're on the topic, I wonder if it'd be possible to use our maki to symbolize points? (e.g., it'd be great to use a campground icon on the map I referenced for the campgrounds). If this is one of those things where it's an easy question but a very hard fix, no worries - I thought I'd just try to tack the idea onto Mamata's issue since it's vaguely related.

**Comment by makella** [comment]
@alexNPS this is on our radar and currently on my plate!
https://github.com/nationalparkservice/npmap-builder/issues/190

**Comment by ntirgis** [comment]
Any estimate on when/if this issue will be tackled?

**Comment by makella** [comment]
@ntirgis I'll look into this tomorrow or Monday.  I'll post when it is implemented! Thanks for putting this back on my radar.

**Comment by makella** [comment]
@nateriwin I know you told me that you need CartoCSS to style the CartoDB layers with the NPMaki icons... is this what you are looking for?

#name_of_layer {
  marker-file: url(http://url-to-marker.com); -- url to specific icon that is selected
  marker-width: 10; -- varies based on if user chooses large, medium, small
  marker-fill: #FF6600; -- varies based on color user selects
  marker-allow-overlap: true;
}

I'm not clear if the teardrop marker needs to be brought in separate from the icon placed inside of it.  If you can help clarify that, I can get you whatever you need to make this happen.

Thanks!
mamata

**Comment by nateirwin** [comment]
That should do it! I'll try to get to this soon.

**Comment by makella** [comment]
A workaround for now is to add the CartoDB layer as a GeoJSON using a url to query the SQL API.  Since this brings in the data as GeoJSON, you have the ability to use the NPMaki styling options.

Here is an example of what that looks like in the Builder 'Add Existing Overlay' window:

![screen shot 2015-06-18 at 10 34 42 am](https://cloud.githubusercontent.com/assets/1566273/8236541/44702a56-15a6-11e5-9000-d8a9f7bdb78e.png)

Here is the URL field broken down into a little more detail:

![cartodb](https://cloud.githubusercontent.com/assets/1566273/8236739/986f44ce-15a7-11e5-8f97-4149c2711ed6.jpg)

To add your own data, you will modify the **User Name**, **Table Name**, and **SQL** in the URL above.

Here is the URL from the example if you would like to  copy/paste and then modify it:

`https://nps.cartodb.com/api/v2/sql?format=GeoJSON&q=SELECT * FROM points_of_interest`

**Comment by alexNPS** [comment]
Hey Mamata, may I bug you? I can't seem to use this workaround. 

I can use a CartoDB layer with a sql query provided by a coworker, of select l.* from animal_locations as l join (select animalid,max(fixdate) as maxdate from animal_locations group by animalid) as m on m.animalid = l.animalid and m.maxdate = l.fixdate and l.projectid =  'KATM_BrownBear' 

I thought it'd be nice if the points used the bear icon, which I think is part of the NPMaki, rather than just a circle / point. So I tried to use this as a geojson layer: 

https://nps-akro-gis.cartodb.com/api/v2/sql?form=GeoJSON&q=select l.* from animal_locations as l join (select animalid,max(fixdate) as maxdate from animal_locations group by animalid) as m on m.animalid = l.animalid and m.maxdate = l.fixdate

Builder doesn't like this; it gives me "The overlay could not be added to the map. The full error message is: The response was not a valid GeoJSON object." 

Even trying a simpler query of https://nps-akro-gis.cartodb.com/api/v2/sql?form=GeoJSON&q=select * from animal_locations yields the same error. Am I doing something wrong? 

Thanks for any insights!

**Comment by nateirwin** [comment]
Hi @alexNPS: Try changing the URL to this:

`https://nps-akro-gis.cartodb.com/api/v2/sql?format=GeoJSON&q=select l.* from animal_locations as l join (select animalid,max(fixdate) as maxdate from animal_locations group by animalid) as m on m.animalid = l.animalid and m.maxdate = l.fixdate`

The parameter is `format`, not `form`.

**Comment by alexNPS** [comment]
Ah, of course! I should've known it was something simple like that. Thank you!

**Comment by nateirwin** [comment]
Closing this one, as I'm going to track this work in #190.
