### ISSUE TITLE
Updating Map Title does not "Take" in CMS

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#219]
When updating a map title, despite browser refresh, etc....map title change does not reflect in CMS version of map. 

http://www.nps.gov/grsm/planyourvisit/juney-whank-falls.htm

http://www.nps.gov/maps/full.html?mapId=200fc2b9-88da-4711-8118-2a719b695338

**Comment by nateirwin** [comment]
How long did you wait to see the change? Due to some recent changes in the NPS.gov content delivery network, cache invalidations can take up to ten minutes.

If it has been longer than that, can you try to invalidate this page: http://www.nps.gov/grsm/planyourvisit/juney-whank-falls.htm. (I can help with that if you don't know how to). I'm not 100% sure how the NPS.gov team is bringing map titles into the CMS, but we may need to figure out how to automate the purge of CMS pages when a map is updated.

**Comment by nateirwin** [comment]
This was resolved by GRSM's web manager.
